### ISSUE TITLE
img "alt" attribute vergeten toe te voegen

### ISSUE THREAD

**Issue by JalalToufik** [jtoufik/your-tribe-squad-page#1]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/112856590/191934384-63fdd831-a276-4ac1-900e-3fd57b7d9e89.png">

**Comment by jtoufik** [comment]
> <img alt="image" width="1278" src="https://user-images.githubusercontent.com/112856590/191934384-63fdd831-a276-4ac1-900e-3fd57b7d9e89.png">

Issue opgelost!

Heb bij elke <img> een "alt toe gevoegd.

**Comment by JalalToufik** [comment]
Issue opgelost!

Heb bij elke  een "alt toe gevoegd.
